### ISSUE TITLE
Feature Suggestion: Send tickets to different staff groups

### ISSUE THREAD

**Issue by do-while-what** [fabston/Telegram-Support-Bot#6]
Firstly, this is an awesome project.
I tried it out the other day and the bot worked flawlessly. Great work!

Coming to the feature suggestion, I think what would make this support bot complete is having the feature to be able to delegate the user messages to different support groups instead of putting them all in one group.

It can become quite difficult to track down the conversations when they’re all lumped together in the same group chat.

This message delegation can be done in two ways:

1. Allow the user to select a support category and have a dedicated group assigned to each of these categories. Eg. When the user starts the chat with the bot, he will be shown two support categories: Payment and Product. Each of these categories will be attached to their respective telegram group of dedicated support members. If he chooses the Payments category, his messages will be forwarded to the Payments support group. Similarly, If he chooses the Product category, his messages will be forwarded to the Products support group.
2. Allocate the support group automatically from a pool of available support groups in a round-robin fashion. Eg. A scenario where there are 10 agents available for support, each with/in their own group. i.e 10 support agents in 10 different support groups. The bot admin can define a list of IDs for these available support groups in the config creating a pool of available support groups. Now, when a user, say John, starts the chat with the bot, he gets assigned to support group 1. Next, when another user, say Emily, starts the chat with the bot, she gets assigned to support group 2 and so on. The tenth user will be assigned to support group 10. When the eleventh user starts the chat with the bot, he will be assigned to support group 1.

I hope the above explanation makes sense if not, please leave a comment and I'll be more than happy to clarify.

Thanks for this amazing project!

**Comment by fabston** [comment]
Hi there,

Glad to hear that your liking the Bot. Your feature request shouldn’t actually be too hard. I’d probably be doing your first option. Not sure when this will be done, but I will add it to the list.

**Comment by do-while-what** [comment]
Thanks for the super quick reply! 
To be honest, I was more intereseted in the second option. It would add the functionality of having a dedicated support mode to the bot. But if you decide to go with the first option, I guess (hope) It wouldn't be too hard for me to modify the code to make it work the way described in the second approach.

Either way, thanks for considering the feature request.

This repo might be helpful for the said feature implementation:
[https://github.com/bostrot/telegram-support-bot](https://github.com/bostrot/telegram-support-bot)

**Comment by fabston** [comment]
Reopening this.
