### ISSUE TITLE
Does not respond to commands

### ISSUE THREAD

**Issue by LeviSnoot** [fabston/Telegram-Support-Bot#7]
## Describe the bug
The bot seems to do everything but respond to or execute commands. I can DM clients but I can't ban, check ticket status or close tickets.

### Steps to reproduce
Install and configure Telegram Support Bot.
Create a service for main.py. Run service.
Write any command in the support chat.

### Expected behavior
Any form of acknowledgement that the command has been recieved.

### Environment
 - OS: Arch Linux 5.13.10-arch1-1

**Comment by fabston** [comment]
Hi,

Appreciate the report. I’ll look into it.

**Comment by LeviSnoot** [comment]
Issue should remain open.

**Comment by LeviSnoot** [comment]
Reopen please.
